"""users table

Revision ID: b26488eb41fd
Revises: 
Create Date: 2018-11-13 21:20:22.251048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26488eb41fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ac_no', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('interest_rate', sa.String(), nullable=True),
    sa.Column('interest_scheme', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('initial_deposit', sa.String(), nullable=True),
    sa.Column('final_deposit', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ac_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deposits')
    # ### end Alembic commands ###
